[package]
name = "bcm2835-sdhcid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fdt = { git = "https://github.com/repnop/fdt.git" }
common = { path = "../../common" }
driver-block = { path = "../driver-block" }

redox-daemon = "0.1"
libredox = "0.1.3"
redox_syscall = { version = "0.5", features = ["std"] }
redox_event = "0.4"
