[package]
name = "ided"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../../common" }
driver-block = { path = "../driver-block" }
libredox = "0.1.3"
log = "0.4"
pcid = { path = "../../pcid" }
redox-daemon = "0.1"
redox_syscall = { version = "0.5", features = ["std"] }
redox_event = "0.4"
