[package]
name = "driver-block"
version = "0.1.0"
edition = "2021"

[dependencies]
executor = { path = "../../executor" }
partitionlib = { path = "../partitionlib" }

libredox = "0.1.3"
log = "0.4"

# TODO: migrate virtio to our executor
futures = { version = "0.3.28", features = ["executor"] }

redox-daemon = "0.1"
redox_syscall = { version = "0.5", features = ["std"] }
redox-scheme = "0.6.2"
