[package]
name = "driver-block"
version = "0.1.0"
edition = "2021"

[dependencies]
partitionlib = { path = "../partitionlib" }

libredox = "0.1.3"
redox_syscall = "0.5"
redox-scheme = { git = "https://gitlab.redox-os.org/redox-os/redox-scheme.git" }
