[package]
name = "ahcid"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.2"
byteorder = "1.2"
log = "0.4"
redox-daemon = "0.1"
redox_syscall = { version = "0.5", features = ["std"] }

common = { path = "../../common" }
driver-block = { path = "../driver-block" }
pcid = { path = "../../pcid" }
libredox = "0.1.3"
redox_event = "0.4"
